// Generated by https://quicktype.io

import 'dart:convert';

Activity activityModelFromJson(String str) => Activity.fromJson(json.decode(str));

String activityModelToJson(Activity data) => json.encode(data.toJson());

class Activities{
  //contenedor de todos los items
  //MAPEO
  List<Activity> items = new List();

  Activities.fromJsonList( List<dynamic> jsonList){

    if (jsonList == null) return;

    jsonList.forEach( (item) {
      final activity = Activity.fromJsonMap(item); 
      items.add(activity);
    });
  }


  // recibir el mapa de todo
}
class Activity {
  String id;
  String person;
  bool status;
  String name;
  String type;
  String date;
  String description;
  String startTime;
  String endTime;
  String classroom;
  String blockCampus;
  int v;

  Activity({
    this.id,
    this.person,
    this.status,
    this.name,
    this.type,
    this.date,
    this.description,
    this.startTime,
    this.endTime,
    this.classroom,
    this.blockCampus,
    this.v,
  });


  Activity.fromJsonMap(Map<String,dynamic> json){
    id= json['_id']; 
    person= json['person']; 
    status= json['status']; 
    name= json['name']; 
    type= json['type']; 
    date= json['date']; 
    description= json['description']; 
    startTime= json['start_time']; 
    endTime= json['end_time']; 
    classroom= json['classroom']; 
    blockCampus= json['block_campus']; 
    v= json['v']; 

    
  }

  factory Activity.fromJson(Map<String, dynamic> json) => new Activity(
    id           : json['_id'], 
    person       : json['person'], 
    status       : json['status'], 
    name         : json['name'], 
    type         : json['type'], 
    date         : json['date'], 
    description  : json['description'],
    startTime    : json['start_time'], 
    endTime      : json['end_time'], 
    classroom    : json['classroom'], 
    blockCampus  : json['block_campus'], 
    v            : json['v'],
    );

    Map<String, dynamic> toJson() => {
         "id"         : id,
                 
        "person"        : person,     
        "status"        : status,     
        "name"          : name,       
        "type"          : type,       
        "date"          : date,       
        "description"   : description,
        "startTime"     : startTime,  
        "endTime"       : endTime,    
        "classroom"     : classroom,  
        "blockCampus"   : blockCampus,
        "v"             : v,          
    };

}
